###
#
# Custom workflow matrix configurations
#
# @link https://github.com/gocodebox/.github/tree/trunk/.github/actions/setup-matrix
#
###
Test PHPUnit:
  exclude:
    # Covered by integration test workflow.
    - PHP: '8.0'
      WP: '5.8'
